### ISSUE TITLE
AttributeError: 'list' object has no attribute 'tree'

### ISSUE THREAD

**Issue by hvelarde** [plone/plone.protect#31]
I have zillions of these on my instance.log:

```python
2015-11-05T17:50:30 ERROR plone.transformchain Unexpected error whilst trying to apply transform chain
Traceback (most recent call last):
  File "/home/abc/xyz/eggs/plone.transformchain-1.0.3-py2.7.egg/plone/transformchain/transformer.py", line 48, in __call__
    newResult = handler.transformIterable(result, encoding)
  File "/home/abc/xyz/eggs/plone.protect-3.0.15-py2.7.egg/plone/protect/auto.py", line 163, in transformIterable
    return self.transform(result, encoding)
  File "/home/abc/xyz/eggs/plone.protect-3.0.15-py2.7.egg/plone/protect/auto.py", line 267, in transform
    root = result.tree.getroot()
AttributeError: 'list' object has no attribute 'tree'
```

is that a bug? Products.CMFPlone == 4.3.4.1.

**Comment by davilima6** [comment]
Yep: Products.CMFPlone#1215

**Comment by hvelarde** [comment]
thanks!

**Comment by mauritsvanrees** [comment]
For clarity, this is fixed in the plone.protect 3.0.16 release from yesterday.

**Comment by hvelarde** [comment]
yes, I saw it and is already installed here; thanks, @mauritsvanrees!
