### ISSUE TITLE
AttributeError: 'list' object has no attribute 'tree'

### ISSUE THREAD

**Issue by agitator** [plone/plone.protect#32]
i get this when creating a plone 4.3.7 site

```
2015-11-11 13:25:35 INFO GenericSetup.rolemap Role / permission map imported.
2015-11-11 13:25:35 INFO GenericSetup.skins Skins tool imported.
2015-11-11 13:25:35 INFO GenericSetup.resourceregistry Stylesheet registry imported.
2015-11-11 13:25:35 INFO GenericSetup.actions Actions tool imported.
2015-11-11 13:25:35 INFO GenericSetup.archetypetool Archetype tool imported.
2015-11-11 13:25:35 ERROR plone.transformchain Unexpected error whilst trying to apply transform chain
Traceback (most recent call last):
  File "/Users/peter/workspace/eggs/plone.transformchain-1.0.4-py2.7.egg/plone/transformchain/transformer.py", line 48, in __call__
    newResult = handler.transformIterable(result, encoding)
  File "/Users/peter/workspace/eggs/plone.protect-3.0.15-py2.7.egg/plone/protect/auto.py", line 163, in transformIterable
    return self.transform(result, encoding)
  File "/Users/peter/workspace/eggs/plone.protect-3.0.15-py2.7.egg/plone/protect/auto.py", line 267, in transform
    root = result.tree.getroot()
AttributeError: 'list' object has no attribute 'tree'

```

**Comment by agitator** [comment]
and later on almost every save/write

**Comment by vincentfretin** [comment]
This is fixed in plone.protect 3.0.16
