### ISSUE TITLE
AttributeError: 'list' object has no attribute 'tree'

### ISSUE THREAD

**Issue by keul** [plone/plone.protect#33]
Using plone.protect 3.0.15 (suggested version from https://pypi.python.org/pypi/plone4.csrffixes/1.0.8) I get some errors in the log:

    2015-11-12 08:33:51 ERROR plone.transformchain Unexpected error whilst trying to apply transform chain
    Traceback (most recent call last):
      File "/srv/webapp/eggs/plone.transformchain-1.0.4-py2.7.egg/plone/transformchain/transformer.py", line 48, in __call__
        newResult = handler.transformIterable(result, encoding)
      File "/srv/webapp/eggs/plone.protect-3.0.15-py2.7.egg/plone/protect/auto.py", line 163, in transformIterable
        return self.transform(result, encoding)
      File "/srv/webapp/eggs/plone.protect-3.0.15-py2.7.egg/plone/protect/auto.py", line 267, in transform
    root = result.tree.getroot()
    AttributeError: 'list' object has no attribute 'tree'

**Comment by agitator** [comment]
https://github.com/plone/plone.protect/issues/32 ;-)
