### ISSUE TITLE
'Forbidden: Form authenticator is invalid' in creating the site in the Plone 4.3

### ISSUE THREAD

**Issue by idgserpro** [plone/plone.protect#35]
If you use plone.protect 3.0.16 and doesn't use plone4.csrffixes, the error below occurs in creating of the Plone Site:
```bash
Traceback (most recent call last):
  File "/home/user/cache-python/eggs/plone.transformchain-1.0.4-py2.7.egg/plone/transformchain/transformer.py", line 48, in __call__
    newResult = handler.transformIterable(result, encoding)
  File "/home/user/cache-python/eggs/plone.protect-3.0.16-py2.7.egg/plone/protect/auto.py", line 158, in transformIterable
    if not self.check():
  File "/home/user/cache-python/eggs/plone.protect-3.0.16-py2.7.egg/plone/protect/auto.py", line 177, in check
    return self._check()
  File "/home/user/cache-python/eggs/plone.protect-3.0.16-py2.7.egg/plone/protect/auto.py", line 201, in _check
    check(self.request, manager=self.key_manager)
  File "/home/user/cache-python/eggs/plone.protect-3.0.16-py2.7.egg/plone/protect/authenticator.py", line 113, in check
    raise Forbidden('Form authenticator is invalid.')
Forbidden: Form authenticator is invalid.
```

This should not be documented?

**Comment by gforcada** [comment]
@idgserpro any good reason for **not** using plone4.csrffixes?

If you want to use plone.protect > 3.x on Plone 4.3 it's [more than recommended](https://plone.org/products/plone/security/advisories/security-vulnerability-20151006-csrf)

**Comment by mauritsvanrees** [comment]
I have added a Compatibility section in the readme and pushed a new release 3.0.17 to PyPI: https://pypi.python.org/pypi/plone.protect/3.0.17

**Comment by idgserpro** [comment]
@mauritsvanrees it was a note so I was thinking. Thanks!
